version: '3.8'

services:
  typesense:
    image: typesense/typesense:29.0
    container_name: typesense
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: >
      --data-dir /data
      --api-key=xyz123
      --listen-port 8108
      --enable-cors
    restart: unless-stopped
